language: node_js
node_js:
  - 4.4.4

services:
  - mongodb

before_script:
  - mongo test --eval "db.getCollection('users').insert({'username':'gimme', 'password':'token'});"
  - mongo test --eval "db.getCollection('users').find({});"

deploy:
  provider: heroku
  api_key:
    secure: "pCm9W/tUTvcQv4VrLOuFyBBAFO84qzSFcYzj9xp191BmBGf/sEaiVl9Gz95geM2OViH4e851ByQ5MSTKwQpn0gsjJSpFWo8RQ10vSind8ZDb0Dktcy0AJfGndNdxxe8ALEkU6Ji1Qu/PUi+iqR68Lz58OaPm1idpuEujPP0SajDJmgPbckeeX8R2Cur7Im0ev/0gei6J36QX+CwlbCZ+tJSFzwq9ry35tmrfYuWadwVRpCYnyihN6GXTvlDUyLp+nF8Lx0uPaRLlBJKDEE4MG3adjIzgw/XN03DUoSC7rQnGGgitWed9Kf84QHdjT5CZKv6rEE268YsnxmhyTK7dJKI9Pq6BMheetBvsVUtFagVOdw3q0Y/GLKc0IooToqfmRIukd2djp3gl3h0xPaYdZTcFWu9pQcTK1N0i0ibffoKOsAPizEwdj/beL4f4Roqnezmy1t1kc/rI+ajh9CcnKWg1T/usMznSrLGU/c05Q7ckopue19Xi5ELAZ0WxPmtLKV1l4wtGBdZD6N3aBOCKFRtBEQwn1u5nxmb/hw7/zTYSr/d5nysJksReQOsHfgpociZXCOCjbD/EWFh4Xghqg1fQS50PCGfGWRo6DbwUtz60qy4Ds6W/oa4ikXQO2mSiZK5yQbMfXnqkiyL1Qy4YWY0Bj3az1LcGg/mFevyrekw="
  app: mo-practical-interview
