language: node_js
node_js:
- 4.4.4
services:
- mongodb
before_script:
- mongo test --eval "db.getCollection('users').insert({'username':'gimme', 'password':'token'});"
- mongo test --eval "db.getCollection('users').find({});"
deploy:
  provider: heroku
  api_key:
    secure: 0tEAaS9nXvtGlby+EGP87FKKKbkcD6IYXJd6M3nOE6Swv5qHL9a7GRBl+mpxHji2fMcewc2dVqg6fdvkqJOtkiX+PLf5uMFOP3/YlG3cAEMw4p6bOh1fqobNXEi6Bqk3Kh54ACk+/+bs9UC/8vjL6b3pOyn1B085QrV0GL6m8cQrS7ycCgwafSEmqbEiPLycRUv0FfJwVTy+oW4EaQaaukATQv2+b8lW5FyoX57iRTkE6dH1m06iMp1cKP0Wknd071Ufb+8cmzV3IiG/miWWiTmFlErhiNMV8eRbxZbY8H+05woblJnQwRjm/JsYQ5lN8cio9SlTnO7RfdcTDwCbp7YmpVz40q99PdElbjm+qIe1yHIUshjeXT2LFXrnsrLDQu8y99CGXFUwwnX3/b0eg2/7rJnFjzIBjGDAd0ZrCflSoTDf5tx5HklzcYTVvK7jMmgcnPccn/lxH4L+R+jG8KIxYCXQjOp6MiCamkYlI4doXuaH29S+sy1Xk+ioM23QD+kUAgTZbQ8t9SU2dIMxS/bEeKrMISiCfs0cMkx5k7sWduGXhA+Csehw45EdTdcQ2FNmEooAhE2lpU6Nx6cssZWkz8TtIxQe74pmj232NJsCpTBrq6cu2PWFQEj+7f8nzDaPJdeGoBCN5GnRq6yH1DznAAMX3N5y/n8IYd7JRhk=
  app: mo-practical-interview
  on:
    repo: witmicko/Practical-Interview-CRUDL-nodejs
